### ISSUE TITLE
change readme file 

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/resume-builder#1]
default readme file, update the readme make it more personalized

**Comment by akadeepesh** [comment]
let me....

**Comment by Rahilsiddique** [comment]
go ahead @shlok-2003

**Comment by shlok-2003** [comment]
@Rahilsiddique I want to know more about this repo for making the file

**Comment by Rahilsiddique** [comment]
cool, this is basically a resume builder website which is quite obvious from the name, I'll be deploying this project in a bit you can take screen shot of that also refer the bigBitPirate repo for readme.md reference

**Comment by Rahilsiddique** [comment]
cool, 1. fork the projects than clone it using `git clone` and after cloning on your local machine open using using code editor of your choice and `run npm` install and then `npm start`,
Also do refer [this](https://resume-builder-two-xi.vercel.app/) the deployed link

tech stack: React.js

**Comment by Rahilsiddique** [comment]
Amazing work shlok !!

**Comment by shlok-2003** [comment]
Hey @Rahilsiddique, I have some few block more to be updated.
Can I make changes again

**Comment by Rahilsiddique** [comment]
yes, go ahead

**Comment by Rahilsiddique** [comment]
hey @shlok-2003, we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. 
Join our community: https://bit.ly/cerritus-coders

Do join
