### ISSUE TITLE
custom name and icon

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/resume-builder#10]
![image](https://user-images.githubusercontent.com/75086395/197752052-98b18614-f886-4af0-820c-8b142a92b65b.png)
right now title and favicon is default, we can personalized with some custom title and icons 

for Icon you are free to use your own idea and title could be resume-builder

**Comment by najeebkp** [comment]
Hi @Rahilsiddique  please assign this to me

**Comment by Rahilsiddique** [comment]
sure @najeebkp, go ahead
also, we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. 
Join our community: https://bit.ly/cerritus-coders
